version: 1
script:
  - rm -rf AppDir || true
  - mkdir -p AppDir/bin
  - cp target/release/taskwarrior-tui AppDir/bin/taskwarrior-tui

AppDir:
  path: ./AppDir

  app_info:
    id: org.taskwarrior-tui.taskwarrior-tui
    name: taskwarrior-tui
    icon: taskwarrior-tui
    version: 0.8.13
    exec: $APPDIR/usr/bin/taskwarrior-tui
    exec_args: $@

  apt:
    arch: amd64
    sources:
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'

    include: []
    exclude: []

  runtime:
    env:
     PATH: '${APPDIR}/usr/bin:${PATH}'

  files:
    exclude:
      - usr/share/man
      - usr/share/doc/*/README.*
      - usr/share/doc/*/changelog.*
      - usr/share/doc/*/NEWS.*
      - usr/share/doc/*/TODO.*

  test:
    fedora:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
      use_host_x: true
    debian:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
      use_host_x: true
    arch:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
      use_host_x: true
    centos:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
      use_host_x: true
    ubuntu:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true

AppImage:
  update-information: None
  sign-key: None
  arch: x86_64
