[settings]
env_shell_expand = true
status.show_env = true

[env]
RUST_TEST_THREADS = "1"
TASKWARRIOR_REPO_URL = "https://github.com/GothenburgBitFactory/taskwarrior.git"
TASKWARRIOR_SOURCE = "v3.3.0"
TASKWARRIOR_SOURCE_DIR = "{{config_root}}/tmp/taskwarrior-src"
TASKWARRIOR_BUILD_DIR = "{{config_root}}/tmp/taskwarrior-build/{{env.TASKWARRIOR_SOURCE}}"
TASKWARRIOR_INSTALL_DIR = "{{config_root}}/tmp/taskwarrior-install/{{env.TASKWARRIOR_SOURCE}}"
TASKWARRIOR_TESTDATA_REPO_URL = "https://github.com/kdheepak/taskwarrior-testdata"
TASKWARRIOR_TESTDATA_REF = "149099b69457404e20e73b428db00c7e88aca8d3"
TASKWARRIOR_TESTDATA_DIR = "{{config_root}}/tests/data"
TASKRC = "{{config_root}}/tests/data/.taskrc"
TASKDATA = "{{config_root}}/tests/data/.task"
TASKWARRIOR_TUI_CONFIG = "{{config_root}}/tests/data/.config"
TASKWARRIOR_TUI_DATA = "{{config_root}}/tests/data/.data"
TASKWARRIOR_TUI_LOG_LEVEL = "debug"
_.path = "{{env.TASKWARRIOR_INSTALL_DIR}}/bin"

[tools]
rust = { version = "latest", postinstall = "mise run ensure-rust-toolchain" }
uv = "latest"
"aqua:Kitware/CMake" = "latest"
"github:jgm/pandoc" = "latest"
"cargo:cross" = "latest"
"cargo:grcov" = "latest"
"cargo:cargo-deb" = "latest"
"cargo:cargo-rpm" = "latest"
"cargo:cargo-aur" = "latest"
