#!/usr/bin/env bash
#MISE description="Import tests/data/export.json into tests/data/.task"
#MISE depends=["clean-taskdata", "setup-testdata"]
set -euo pipefail

task import rc.hooks=0 tests/data/export.json
