name: taskwarrior-tui
base: core20
version: git
summary: A terminal user interface for taskwarrior
description: |
  A terminal user interface for taskwarrior to manage your tasks efficiently.

grade: stable
confinement: strict

parts:
  taskwarrior:
    plugin: cmake
    override-build: |
      mkdir -p build
      cd build
      cmake \
        -DBUILD_SYNC=OFF -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_STAGE/cmake \
        $SNAPCRAFT_PART_SRC
      make
      make install
    source: https://github.com/GothenburgBitFactory/taskwarrior.git
    source-type: git
    build-packages:
      - build-essential

  taskwarrior-tui:
    plugin: rust
    source: .

apps:
  taskwarrior-tui:
    command: bin/taskwarrior-tui
  task:
    command: bin/task
