name: taskwarrior-tui
base: core18
version: git
summary: A terminal user interface for taskwarrior
description: |
  A terminal user interface for taskwarrior to manage your tasks efficiently.

grade: stable
confinement: strict

parts:
  taskwarrior:
    plugin: cmake
    source: https://git.tasktools.org/scm/tm/task.git
    source-type: git
    build-packages:
      - build-essential
      - libgnutls-dev
      - uuid-dev

  taskwarrior-tui:
    plugin: rust
    source: .

apps:
  taskwarrior-tui:
    command: bin/taskwarrior-tui
  task:
    command: task
