name: taskwarrior-tui
base: core20
version: git
summary: A terminal user interface for taskwarrior
description: |
  A terminal user interface for taskwarrior to manage your tasks efficiently.

grade: stable
confinement: strict

apps:
  task:
    command: usr/local/bin/task

  taskwarrior-tui:
    command: bin/taskwarrior-tui

parts:
  task:
    plugin: cmake
    source: https://github.com/GothenburgBitFactory/taskwarrior.git
    source-type: git
    build-packages:
      - build-essential
      - gnutls-dev
      - uuid-dev
    organize:
      - usr/local/bin/task: bin/task

  taskwarrior-tui:
    plugin: rust
    source: .
