name: taskwarrior-tui
base: core24
version: git
summary: A terminal user interface for taskwarrior
description: |
  A terminal user interface for taskwarrior to manage your tasks efficiently.

grade: stable
confinement: strict

apps:
  task:
    command: usr/bin/task
    environment:
      PATH: $SNAP/usr/bin:$SNAP/usr/local/bin/:$PATH:$SNAP/bin/:$PATH
      MANPATH: $SNAP/usr/share/man

  taskwarrior-tui:
    command: bin/taskwarrior-tui
    desktop: usr/share/applications/taskwarrior-tui.desktop
    environment:
      PATH: $SNAP/usr/bin:$SNAP/usr/local/bin/:$PATH:$SNAP/bin/:$PATH
      MANPATH: $SNAP/usr/share/man

parts:
  task:
    plugin: nil
    stage-packages:
      - taskwarrior

  taskwarrior-tui:
    plugin: rust
    source: .

  desktop-and-man:
    plugin: dump
    source: .
    organize:
      docs/taskwarrior-tui.desktop: usr/share/applications/taskwarrior-tui.desktop
      docs/taskwarrior-tui.1: usr/share/man/man1/taskwarrior-tui.1
