name: taskwarrior-tui
base: core20
version: git
summary: A terminal user interface for taskwarrior
description: |
  A terminal user interface for taskwarrior to manage your tasks efficiently.

grade: stable
confinement: strict

apps:
  task:
    command: bin/task
    environment:
      PATH: $SNAP/usr/bin:$SNAP/usr/local/bin/:$PATH:$SNAP/bin/:$PATH

  taskwarrior-tui:
    command: bin/taskwarrior-tui
    environment:
      PATH: $SNAP/usr/bin:$SNAP/usr/local/bin/:$PATH:$SNAP/bin/:$PATH

parts:
  task:
    plugin: cmake
    source: https://github.com/GothenburgBitFactory/taskwarrior.git
    source-type: git
    build-packages:
      - build-essential
      - gnutls-dev
      - uuid-dev
  taskwarrior-tui:
    plugin: rust
    source: .
