name: taskwarrior-tui
base: core18
version: git
summary: A terminal user interface for taskwarrior
description: |
  A terminal user interface for taskwarrior to manage your tasks efficiently.

grade: stable
confinement: devmode

parts:
  taskwarrior-tui:
    plugin: rust
    source: .

apps:
  taskwarrior-tui:
    command: bin/taskwarrior-tui
    plugs:
      - home

layout:
  /usr/bin/task:
    bind: $SNAP_DATA/usr/bin/task
