name: CD

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  generate_coverage:
    uses: ./.github/workflows/generate_coverage.yml

  homebrew:
    name: Bump Homebrew formula
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: Update Homebrew formula
        if: startsWith(github.ref, 'refs/tags/')
        uses: dawidd6/action-homebrew-bump-formula@v7
        with:
          token: ${{secrets.HOMEBREW_TOKEN}}
          formula: taskwarrior-tui

  deb:
    name: Publish deb package
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-${{ runner.os }}
      - run: cargo build --release
      - name: Build deb package
        run: mise run taskwarrior-tui:package-deb
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: taskwarrior-tui-deb
          path: target/debian/taskwarrior-tui.deb
      - name: Releasing assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/debian/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rpm:
    name: Publish rpm package
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-${{ runner.os }}
      - run: cargo build --release
      - name: Install rpm
        run: sudo apt-get update && sudo apt-get install -y rpm
      - name: Build rpm package
        run: mise run taskwarrior-tui:package-rpm
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: taskwarrior-tui-rpm
          path: target/release/rpmbuild/RPMS/x86_64/taskwarrior-tui-*.x86_64.rpm
      - name: Releasing assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/rpmbuild/RPMS/x86_64/taskwarrior-tui-*.x86_64.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  aur:
    name: Publish aur package
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-${{ runner.os }}
      - run: cargo build --release
      - name: Build aur package
        run: mise run taskwarrior-tui:package-aur
