on: [pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          mise_toml: |
            [tools]
            rust = { version = "latest", profile = "minimal", components = "cargo" }
            uv = "latest"
            cmake = "latest"
      - name: Install Taskwarrior build dependencies
        run: sudo apt-get update && sudo apt-get install -y uuid-dev uuid-runtime
      - name: Build Taskwarrior from source
        run: uv run scripts/build_taskwarrior.py
      - name: Add Taskwarrior to PATH
        run: echo "$GITHUB_WORKSPACE/target/taskwarrior-install/stable/bin" >> "$GITHUB_PATH"
      - run: |
          # prepare taskwarrior, initial setup
          task rc.confirmation=off || echo 0
      - name: Install testdata
        uses: actions/checkout@v6
        with:
          repository: kdheepak/taskwarrior-testdata
          path: taskwarrior-testdata
      - run: cargo test --workspace -- --nocapture
        env:
          TASKRC: taskwarrior-testdata/.taskrc
          TASKDATA: taskwarrior-testdata/.task
          RUST_BACKTRACE: full


  generate_coverage:
    uses: ./.github/workflows/generate_coverage.yml
    # Avoid double-compiling taskwarrior if not cached, or wasting CI time if tests fail
    needs: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          mise_toml: |
            [tools]
            rust = { version = "nightly", profile = "minimal", components = "rustfmt" }
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: cargo clippy -- -D warnings
