on: [pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: mise run taskwarrior-tui:cargo-check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - name: Install Taskwarrior build dependencies
        run: sudo apt-get update && sudo apt-get install -y uuid-dev uuid-runtime
      - name: Build Taskwarrior from source
        run: mise run taskwarrior-tui:build-taskwarrior
      - run: |
          # prepare taskwarrior, initial setup
          mise exec -- task rc.confirmation=off || echo 0
      - run: mise run taskwarrior-tui:cargo-test
        env:
          RUST_BACKTRACE: full


  generate_coverage:
    uses: ./.github/workflows/generate_coverage.yml
    # Avoid double-compiling taskwarrior if not cached, or wasting CI time if tests fail
    needs: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: mise run taskwarrior-tui:cargo-fmt

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: mise run taskwarrior-tui:cargo-clippy
